cat > _config.yml <<'YML'
minimal_mistakes_skin: "default"

locale: "ko"
title: "권덕현의 비밀스런 공간"
name: "권덕현"
description: "반갑다 인사 씨게박는다."
url: "https://cicada31113.github.io"
baseurl: ""

timezone: "Asia/Seoul"

author:
  name: "권덕현"
  bio: "기술과 이야기가 있는 공간"
  location: "대한민국"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cicada31113"

footer:
  since: "2025"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cicada31113"

# 레포에 테마 소스가 이미 포함된 Fork 구조라면 theme/remote_theme 불필요.
# 만약 테마 소스가 없다면 아래 줄 주석 해제:
# remote_theme: "mmistakes/minimal-mistakes"

plugins:
  # - jekyll-paginate   # 문제시 비활성 유지
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true

permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..6

encoding: "utf-8"

include:
  - _pages
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README
  - LICENSE
  - .sass-cache
  - .jekyll-cache
  - .gitignore
keep_files:
  - .git
YML
